package com.atguigu.cxf.spring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-12-16T19:43:47.078+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.atguigu.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "info", targetNamespace = "http://webservice.atguigu.com/", className = "com.atguigu.webservice.Info")
    @WebMethod
    @ResponseWrapper(localName = "infoResponse", targetNamespace = "http://webservice.atguigu.com/", className = "com.atguigu.webservice.InfoResponse")
    public java.lang.String info(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
